# ParlaMint dataset processing

Input data: ParlaMint dataset (handle), where the data is merged together into a master preprocessed dataset, to be used for all of the analysis. Specifically, we include the following data:

Sample dataset (for replicability purposes:)
- ```Sample/ParlaMint-SI_5.1.txt``` (text files, to acquire the texts)
- ```Sample/ParlaMint-SI_5.1.connllu``` (metadata and sentiment metadata files)

Full dataset available for download on the CLARIN.SI repository: 
> Erjavec, Tomaž; et al., 2025, **Multilingual comparable corpora of parliamentary debates ParlaMint 5.0**, Slovenian language resource repository CLARIN.SI, ISSN 2820-4042, 
http://hdl.handle.net/11356/2004.


Output:
- Pre-processed and merged master dataset [ParlaMint-SI_5.1_master.tsv](../Sample/Datasets/ParlaMint-SI_5.1_master.tsv)

In [1]:
import pandas as pd
import os
import glob

In [2]:
#Sample datasets, replace with actual ParlaMint dataset from CLARIN.SI repository entry
text_dir = "../Sample/ParlaMint-SI.txt"
conllu_dir = "../Sample/ParlaMint-SI.conllu"

In [3]:
# Text files to extrac ID and text
text_files = glob.glob(os.path.join(text_dir, '*', '*.txt'))

#Session metadata
text_meta = glob.glob(os.path.join(text_dir, '*', '*.tsv'))

#Sentiment-related metadata
sent_files = glob.glob(os.path.join(conllu_dir, '**', '*-ana-meta-en.tsv'))

print(text_files)

['../Sample/ParlaMint-SI.txt/2014/ParlaMint-SI_2014-01-27-SDZ6-Redna-21.txt', '../Sample/ParlaMint-SI.txt/2014/ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.txt', '../Sample/ParlaMint-SI.txt/2014/ParlaMint-SI_2014-01-28-SDZ6-Redna-21.txt', '../Sample/ParlaMint-SI.txt/2014/ParlaMint-SI_2014-01-30-SDZ6-Redna-21.txt', '../Sample/ParlaMint-SI.txt/2014/ParlaMint-SI_2014-01-29-SDZ6-Redna-21.txt', '../Sample/ParlaMint-SI.txt/2022/ParlaMint-SI_2022-02-02-SDZ8-Redna-29.txt', '../Sample/ParlaMint-SI.txt/2022/ParlaMint-SI_2022-01-26-SDZ8-Izredna-94.txt', '../Sample/ParlaMint-SI.txt/2022/ParlaMint-SI_2022-02-01-SDZ8-Redna-29.txt', '../Sample/ParlaMint-SI.txt/2022/ParlaMint-SI_2022-01-31-SDZ8-Redna-29.txt', '../Sample/ParlaMint-SI.txt/2022/ParlaMint-SI_2022-01-13-SDZ8-Izredna-93.txt', '../Sample/ParlaMint-SI.txt/2007/ParlaMint-SI_2007-01-31-SDZ4-Redna-24.txt', '../Sample/ParlaMint-SI.txt/2007/ParlaMint-SI_2007-01-30-SDZ4-Redna-24.txt', '../Sample/ParlaMint-SI.txt/2007/ParlaMint-SI_2007-01-29-SDZ4-Redna-24.txt', '../Sample/ParlaMint-SI.txt/2007/ParlaMint-SI_2007-02-01-SDZ4-Redna-24.txt', '../Sample/ParlaMint-SI.txt/2007/ParlaMint-SI_2007-02-02-SDZ4-Redna-24.txt', '../Sample/ParlaMint-SI.txt/2000/ParlaMint-SI_2000-11-17-SDZ3-Izredna-01.txt', '../Sample/ParlaMint-SI.txt/2000/ParlaMint-SI_2000-11-16-SDZ3-Izredna-01.txt', '../Sample/ParlaMint-SI.txt/2000/ParlaMint-SI_2000-11-10-SDZ3-Redna-01.txt', '../Sample/ParlaMint-SI.txt/2000/ParlaMint-SI_2000-10-27-SDZ3-Redna-01.txt', '../Sample/ParlaMint-SI.txt/2000/ParlaMint-SI_2000-11-21-SDZ3-Izredna-01.txt']

In [4]:
id = []
texts = []
#Processing text files
for file in text_files:
    with open(file, 'r', encoding="utf-8") as infile:
        for line in infile:
            if '\t' in line:
                parts = line.strip().split('\t')
                if len(parts) == 2:
                    id.append(parts[0])
                    texts.append(parts[1])


df_texts = pd.DataFrame({'ID': id, 'Text':texts})
print("df_meta shape: ", df_texts.shape)

df_texts.head()

df_meta shape:  (3534, 2)

,ID,Text
0,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u1,Spoštovane kolegice poslanke in kolegi poslanc...
1,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u2,"Hvala lepa za besedo. Zdaj Vlada predlaga, da ..."
2,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u3,Hvala tudi vam. O tej zahtevi ni razprave in o...
3,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u4,"Hvala lepa za besedo. To, kar se dogaja z nove..."
4,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u5,"Hvala. Naj vas opozorim, da tudi o tej zahtevi..."

In [5]:
df_meta = pd.DataFrame()
for file in text_meta:
    df = pd.read_csv(file, sep='\t', encoding='utf-8')
    df_meta = pd.concat([df_meta, df])

df_meta.head()

cols = ['Text_ID', 'Title', 'Body', 'Session', 'Sitting', 'Agenda', 'Lang']
df_meta = df_meta.drop(columns=cols)

print("df_meta shape: ", df_meta.shape)
df_meta.head()

df_meta shape:  (3534, 17)

,ID,Date,Term,Meeting,Subcorpus,Speaker_role,Speaker_MP,Speaker_minister,Speaker_party,Speaker_party_name,Party_status,Party_orientation,Speaker_ID,Speaker_name,Speaker_gender,Speaker_birth,Topic
0,ParlaMint-SI_2014-01-29-SDZ6-Redna-21.u1,2014-01-29,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,Social Democrats,Coalition,Centre-left,VeberJanko,"Veber, Janko",M,1960,Other
1,ParlaMint-SI_2014-01-29-SDZ6-Redna-21.u2,2014-01-29,6. mandat,Redna,Reference,Regular,MP,notMinister,SDS,Slovenian Democratic Party,Opposition,Right,VizjakAndrej,"Vizjak, Andrej",M,1964,Government Operations
2,ParlaMint-SI_2014-01-29-SDZ6-Redna-21.u3,2014-01-29,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,Social Democrats,Coalition,Centre-left,VeberJanko,"Veber, Janko",M,1960,Mix
3,ParlaMint-SI_2014-01-29-SDZ6-Redna-21.u4,2014-01-29,6. mandat,Redna,Reference,Regular,MP,notMinister,-,-,-,-,BratušekAlenka,"Bratušek, Alenka",F,1970,Government Operations
4,ParlaMint-SI_2014-01-29-SDZ6-Redna-21.u5,2014-01-29,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,Social Democrats,Coalition,Centre-left,VeberJanko,"Veber, Janko",M,1960,Other

In [6]:
df_sent = pd.DataFrame()
for file in sent_files:
    df = pd.read_csv(file, sep='\t', encoding='utf-8')
    df_sent = pd.concat([df_sent, df])

df_sent = df_sent[df_sent['Element'] == 'u']
cols = ['ID', 'Senti_3', 'Senti_6', 'Senti_n', 'Sents', 'Words', 'Tokens']
df_sent = df_sent[cols].reset_index(drop=True)
df_sent['ID'] = df_sent['ID'].str.replace(".ana", "", regex=False)

print("df_sent shape: ", df_sent.shape)
df_sent.head()

df_sent shape:  (3534, 7)

,ID,Senti_3,Senti_6,Senti_n,Sents,Words,Tokens
0,ParlaMint-SI_2014-01-28-SDZ6-Redna-21.u1,Positive,mixed positive,4.03,20,384,443
1,ParlaMint-SI_2014-01-28-SDZ6-Redna-21.u2,Neutral,neutral positive,3.07,18,351,397
2,ParlaMint-SI_2014-01-28-SDZ6-Redna-21.u3,Neutral,neutral positive,2.92,3,30,35
3,ParlaMint-SI_2014-01-28-SDZ6-Redna-21.u4,Neutral,neutral negative,2.29,22,553,609
4,ParlaMint-SI_2014-01-28-SDZ6-Redna-21.u5,Neutral,neutral positive,3.00,3,19,22

In [7]:
df = pd.merge(pd.merge(df_texts, df_meta, on='ID'), df_sent, on='ID')

print("df shape: ", df.shape)
df.head()

df shape:  (3534, 24)

,ID,Text,Date,Term,Meeting,Subcorpus,Speaker_role,Speaker_MP,Speaker_minister,Speaker_party,...,Speaker_name,Speaker_gender,Speaker_birth,Topic,Senti_3,Senti_6,Senti_n,Sents,Words,Tokens
0,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u1,Spoštovane kolegice poslanke in kolegi poslanc...,2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Mix,Neutral,neutral positive,3.21,25,504,570
1,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u2,"Hvala lepa za besedo. Zdaj Vlada predlaga, da ...",2014-01-27,6. mandat,Redna,Reference,Regular,MP,notMinister,SDS,...,"Tanko, Jože",M,1956,Macroeconomics,Negative,negative,0.00,25,419,481
2,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u3,Hvala tudi vam. O tej zahtevi ni razprave in o...,2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Mix,Neutral,neutral positive,3.10,18,265,310
3,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u4,"Hvala lepa za besedo. To, kar se dogaja z nove...",2014-01-27,6. mandat,Redna,Reference,Regular,MP,notMinister,SDS,...,"Tanko, Jože",M,1956,Public Lands,Negative,negative,0.00,28,592,684
4,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u5,"Hvala. Naj vas opozorim, da tudi o tej zahtevi...",2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Other,Neutral,neutral negative,1.84,28,405,471

In [8]:
#Dataset saved as CSV/TSV
df.to_csv("../Sample/Datasets/ParlaMint-SI_5.1_master.tsv", sep='\t', encoding='utf-8', index=False)